services:
  postgres:
    image: postgres:16-alpine
    container_name: venta-hexagonal-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: venta_user
      POSTGRES_PASSWORD: venta_pass
      POSTGRES_DB: venta_hexagonal
    ports:
      - "5432:5432"
    volumes:
      - venta_hexagonal_data:/var/lib/postgresql/data

volumes:
  venta_hexagonal_data: